/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdventuresRouteImport } from './routes/adventures'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CustomTripsRouteImport } from './routes/custom-trips'
import { Route as DestinationsRouteImport } from './routes/destinations'
import { Route as GroupToursRouteImport } from './routes/group-tours'
import { Route as TripsIndexRouteImport } from './routes/trips.index'
import { Route as TripsSlugRouteImport } from './routes/trips.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdventuresRoute = AdventuresRouteImport.update({
  id: '/adventures',
  path: '/adventures',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomTripsRoute = CustomTripsRouteImport.update({
  id: '/custom-trips',
  path: '/custom-trips',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinationsRoute = DestinationsRouteImport.update({
  id: '/destinations',
  path: '/destinations',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupToursRoute = GroupToursRouteImport.update({
  id: '/group-tours',
  path: '/group-tours',
  getParentRoute: () => rootRouteImport,
} as any)
const TripsIndexRoute = TripsIndexRouteImport.update({
  id: '/trips/',
  path: '/trips/',
  getParentRoute: () => rootRouteImport,
} as any)
const TripsSlugRoute = TripsSlugRouteImport.update({
  id: '/trips/$slug',
  path: '/trips/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/adventures': typeof AdventuresRoute
  '/contact': typeof ContactRoute
  '/custom-trips': typeof CustomTripsRoute
  '/destinations': typeof DestinationsRoute
  '/group-tours': typeof GroupToursRoute
  '/trips/$slug': typeof TripsSlugRoute
  '/trips/': typeof TripsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/adventures': typeof AdventuresRoute
  '/contact': typeof ContactRoute
  '/custom-trips': typeof CustomTripsRoute
  '/destinations': typeof DestinationsRoute
  '/group-tours': typeof GroupToursRoute
  '/trips/$slug': typeof TripsSlugRoute
  '/trips': typeof TripsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/adventures': typeof AdventuresRoute
  '/contact': typeof ContactRoute
  '/custom-trips': typeof CustomTripsRoute
  '/destinations': typeof DestinationsRoute
  '/group-tours': typeof GroupToursRoute
  '/trips/$slug': typeof TripsSlugRoute
  '/trips/': typeof TripsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/adventures'
    | '/contact'
    | '/custom-trips'
    | '/destinations'
    | '/group-tours'
    | '/trips/$slug'
    | '/trips/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/adventures'
    | '/contact'
    | '/custom-trips'
    | '/destinations'
    | '/group-tours'
    | '/trips/$slug'
    | '/trips'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/adventures'
    | '/contact'
    | '/custom-trips'
    | '/destinations'
    | '/group-tours'
    | '/trips/$slug'
    | '/trips/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdventuresRoute: typeof AdventuresRoute
  ContactRoute: typeof ContactRoute
  CustomTripsRoute: typeof CustomTripsRoute
  DestinationsRoute: typeof DestinationsRoute
  GroupToursRoute: typeof GroupToursRoute
  TripsSlugRoute: typeof TripsSlugRoute
  TripsIndexRoute: typeof TripsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adventures': {
      id: '/adventures'
      path: '/adventures'
      fullPath: '/adventures'
      preLoaderRoute: typeof AdventuresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/custom-trips': {
      id: '/custom-trips'
      path: '/custom-trips'
      fullPath: '/custom-trips'
      preLoaderRoute: typeof CustomTripsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destinations': {
      id: '/destinations'
      path: '/destinations'
      fullPath: '/destinations'
      preLoaderRoute: typeof DestinationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/group-tours': {
      id: '/group-tours'
      path: '/group-tours'
      fullPath: '/group-tours'
      preLoaderRoute: typeof GroupToursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trips/': {
      id: '/trips/'
      path: '/trips'
      fullPath: '/trips/'
      preLoaderRoute: typeof TripsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trips/$slug': {
      id: '/trips/$slug'
      path: '/trips/$slug'
      fullPath: '/trips/$slug'
      preLoaderRoute: typeof TripsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdventuresRoute: AdventuresRoute,
  ContactRoute: ContactRoute,
  CustomTripsRoute: CustomTripsRoute,
  DestinationsRoute: DestinationsRoute,
  GroupToursRoute: GroupToursRoute,
  TripsSlugRoute: TripsSlugRoute,
  TripsIndexRoute: TripsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
